packaging_format = 2

id = "nostr_catalog"
name = "Nostr YunoHost Catalogue"
description.en = "Decentralised YunoHost application catalogue using Nostr"
version = "0.1~ynh9"
maintainers = ["Nostr YunoHost contributors"]

[upstream]
license = "AGPL-3.0-or-later"
website = "https://github.com/nostr-yunohost/nostr-yunohost"
code = "https://github.com/nostr-yunohost/nostr-yunohost"

[integration]
yunohost = ">= 12.0"
architectures = ["amd64", "arm64", "armhf"]
multi_instance = false
ldap = false
sso = false
disk = "100M"
ram.build = "50M"
ram.runtime = "100M"

[resources]
    [resources.sources.main]
        url = "https://github.com/imattau/nostr-yunohost/releases/download/v0.1.1/nostr-yunohost-linux-amd64.tar.gz"
        sha256 = "f6b5d018169ae7aa319c4e51567160464bdf44d82f03fc604b268b76a035eab2"
        format = "tar.gz"
        extract = false
        autoupdate.strategy = "latest_github_release"
        autoupdate.asset = "nostr-yunohost-linux-amd64.tar.gz"

        [resources.sources.main.arm64]
        url = "https://github.com/imattau/nostr-yunohost/releases/download/v0.1.1/nostr-yunohost-linux-arm64.tar.gz"
        sha256 = "216b22cf47e50543560eaa75f4f32fb9acc625778eb8b663ddac19a37ddad9f3"

        [resources.sources.main.armhf]
        url = "https://github.com/imattau/nostr-yunohost/releases/download/v0.1.1/nostr-yunohost-linux-armv7.tar.gz"
        sha256 = "590e6606ace73e9ba14d7c79c534b8ca9f8e8daf48df72fdbf2bb931224c5f88"

    [resources.system_user]
