#!/bin/bash

source "$(dirname "$0")/_common.sh"
source /usr/share/yunohost/helpers

ynh_backup --src_path="$install_dir"
ynh_backup --src_path="/etc/nostr-catalogd"
ynh_backup --src_path="$catalog_config"
ynh_backup --src_path="/etc/systemd/system/$service_name.service"
