#!/bin/bash

source "$(dirname "$0")/_common.sh"
source /usr/share/yunohost/helpers

ynh_abort_if_errors

ynh_script_progression "Stopping nostr-catalogd..."
ynh_systemd_action --service_name="$service_name" --action="stop" || true
remove_refresh_timer
yunohost service remove "$service_name" || true
ynh_remove_systemd_config

update_catalog_registration remove

ynh_secure_remove --file="$install_dir"
ynh_secure_remove --file="/var/lib/nostr-catalogd"
ynh_secure_remove --file="$env_file"
ynh_secure_remove --file="$publisher_key_file"
ynh_secure_remove --file="$publisher_npub_file"

ynh_script_progression "Removal complete"
