#!/bin/bash

source "$(dirname "$0")/_common.sh"
source /usr/share/yunohost/helpers

ynh_abort_if_errors

ynh_script_progression "Stopping nostr-catalogd..."
ynh_systemd_action --service_name="$service_name" --action="stop" || true

ynh_script_progression "Updating nostr-catalogd..."
ynh_setup_source --dest_dir="$install_dir" --keep="catalogue-cache.json"
if [ ! -x "$install_dir/nostr-catalogd" ]; then
	ynh_die "The core release did not contain nostr-catalogd"
fi
chmod 750 "$install_dir/nostr-catalogd" "$install_dir/nostr-ynh"
chmod -R o-rwx "$install_dir"
chown -R "$app:$app" "$install_dir"

render_daemon_env
ynh_add_config --template="apps_catalog.yml" --destination="/etc/yunohost/apps_catalog.yml"
ynh_add_systemd_config
ynh_systemd_action --service_name="$service_name" --action="start"

ynh_script_progression "Upgrade complete"
